# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2ab346b412f902266caadddeae3940329be75be71ea41b72bd7af4fab2c972be9f9f8902a79126a670b5dd9e603a0fcbc961c33788da49de424edee33ffd508c

test:
  secret_key_base: 9b52a25ded8861a1c23feaea82b0f3a4ff68dfc86da809da2f67aabb4e0a52b2c345a0249a8edb8cdf872be86706a352a39bda8a9bdb66e9430988e7b0b31e0b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
